linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gochecknoinits
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - stylecheck
    - unconvert
    - unparam
    - gosec
    - revive
    - gochecknoglobals
  disable:
    - dupl
    - lll
    - maligned
    - goconst
    - depguard

linters-settings:
  errcheck:
    ignore: fmt:.*

run:
  modules-download-mode: vendor