name: Release

on:
  pull_request:
    types: closed

jobs:
  tag:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  goreleaser:
    runs-on: ubuntu-latest
    needs: [tag]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version:  latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ needs.tag.outputs.version }}
